<?php
		
		/* UTF-8 TEST
		
			中文汉字漢字
		
		*/
		
						/*
						
							This file is from the HoldOffHunger/convert-british-to-american-spellings open-source project.
							
							Author: HoldOffHunger
							License: BSD 3-Clause
							URL: https://github.com/HoldOffHunger/convert-british-to-american-spellings
						
						*/
				
				/* AmericanBritishWords_K
					
					Class for American/British spelling variants for all words beginning with : K.
					
				*/

	class AmericanBritishWords_K {
			/* __construct($args)
			
				Constructor.
				
				Nothing to do here.
			
			*/
			
		public function __construct($args) {
			return TRUE;
		}
		
			/* AmericanBritishWords()
			
				List of US/UK spellings for words starting with : K.
			
			*/

		public function AmericanBritishWords() {
			return [
				'kabbalah'=>['cabala', 'kabbala', 'kabala', 'cabbala', 'cabbalah',],
				'kablukovov'=>['kablukovov', 'kablukovoff',],
				'kachusovov'=>['kachusovov', 'kachusovoff',],
				'kadnikovov'=>['kadnikovov', 'kadnikovoff',],
				'kainogenesis'=>'cainogenesis',
				'kainogenetic'=>'cainogenetic',
				'kainogenetically'=>'cainogenetically',
				'kalganovov'=>['kalganovov', 'kalganovoff',],
				'kamenevev'=>['kamenevev', 'kameneveff',],
				'kane'=>'kanae',
				'kaolinization\'s'=>'kaolinisation\'s',
				'kaolinization'=>'kaolinisation',
				'kaolinizations'=>'kaolinisations',
				'kaolinize'=>'kaolinise',
				'kaolinized'=>'kaolinised',
				'kaolinizes'=>'kaolinises',
				'kaolinizing'=>'kaolinising',
				'kapralovov'=>['kapralovov', 'kapralovoff',],
				'kapranovov'=>['kapranovov', 'kapranovoff',],
				'karandashovov'=>['karandashovov', 'karandashovoff',],
				'karaulovov'=>['karaulovov', 'karaulovoff',],
				'karavayevev'=>['karavayevev', 'karavayeveff',],
				'karbainovov'=>['karbainovov', 'karbainovoff',],
				'karetnikovov'=>['karetnikovov', 'karetnikovoff',],
				'karevev'=>['karevev', 'kareveff',],
				'kariyevev'=>['kariyevev', 'kariyeveff',],
				'karnaukhovov'=>['karnaukhovov', 'karnaukhovoff',],
				'kartashovov'=>['kartashovov', 'kartashovoff',],
				'kartashyovov'=>['kartashyovov', 'kartashyovoff',],
				'kashnikovov'=>['kashnikovov', 'kashnikovoff',],
				'kasyanovov'=>['kasyanovov', 'kasyanovoff',],
				'katayevev'=>['katayevev', 'katayeveff',],
				'kazakovov'=>['kazakovov', 'kazakovoff',],
				'kazankovov'=>['kazankovov', 'kazankovoff',],
				'kazantsevev'=>['kazantsevev', 'kazantseveff',],
				'kazarezovov'=>['kazarezovov', 'kazarezovoff',],
				'kebab\'s'=>['kebob\'s', 'kabob\'s',],
				'kebab'=>['kabob', 'kebob',],
				'kebabs'=>['kabobs', 'kebobs',],
				'ked'=>'kaed',
				'kedrovov'=>['kedrovov', 'kedrovoff',],
				'Keizer\'s'=>'Keiser\'s',
				'Keizer'=>'Keiser',
				'kellia'=>'koellia',
				'kembed'=>'kemboed',
				'kenneled'=>'kennelled',
				'kenneling'=>'kennelling',
				'kenogenesis'=>'cenogenesis',
				'kenogenetic'=>'cenogenetic',
				'kenogenetically'=>'cenogenetically',
				'Keppel\'s'=>'Koeppel\'s',
				'Keppel'=>'Koeppel',
				'keratinization\'s'=>'keratinisation\'s',
				'keratinization'=>'keratinisation',
				'keratinizations'=>'keratinisations',
				'keratinize'=>'keratinise',
				'keratinized'=>'keratinised',
				'keratinizes'=>'keratinises',
				'keratinizing'=>'keratinising',
				'Kerin\'s'=>'Krein\'s',
				'Kerin'=>'Krein',
				'kerneled'=>'kernelled',
				'kerneling'=>'kernelling',
				'kerosene\'s'=>'kerosine\'s',
				'kerosene'=>'kerosine',
				'kerosenes'=>'kerosines',
				'ketchup\'s'=>['catsup\'s', 'catchup\'s',],
				'ketchup'=>['catsup', 'catchup',],
				'ketchups'=>['catsups', 'catchups',],
				'ketonemia'=>'ketonaemia',
				'ketonization\'s'=>'ketonisation\'s',
				'ketonization'=>'ketonisation',
				'ketonizations'=>'ketonisations',
				'ketonize'=>'ketonise',
				'ketonizes'=>'ketonises',
				'khabalovov'=>['khabalovov', 'khabalovoff',],
				'khabarovov'=>['khabarovov', 'khabarovoff',],
				'khalipovov'=>['khalipovov', 'khalipovoff',],
				'khanipovov'=>['khanipovov', 'khanipovoff',],
				'khantsevev'=>['khantsevev', 'khantseveff',],
				'kharitonovov'=>['kharitonovov', 'kharitonovoff',],
				'kharlamovov'=>['kharlamovov', 'kharlamovoff',],
				'khlebnikovov'=>['khlebnikovov', 'khlebnikovoff',],
				'khlebovov'=>['khlebovov', 'khlebovoff',],
				'khmelnovov'=>['khmelnovov', 'khmelnovoff',],
				'khokhlachyovov'=>['khokhlachyovov', 'khokhlachyovoff',],
				'kholodovov'=>['kholodovov', 'kholodovoff',],
				'khomkolovov'=>['khomkolovov', 'khomkolovoff',],
				'khorkovov'=>['khorkovov', 'khorkovoff',],
				'khramovov'=>['khramovov', 'khramovoff',],
				'khrebtovov'=>['khrebtovov', 'khrebtovoff',],
				'khromovov'=>['khromovov', 'khromovoff',],
				'khrushchevev'=>['khrushchevev', 'khrushcheveff',],
				'khudovekovov'=>['khudovekovov', 'khudovekovoff',],
				'khudyakovov'=>['khudyakovov', 'khudyakovoff',],
				'kickoff'=>'kick-off',
				'kickoffs'=>'kick-offs',
				'kiddie\'s'=>'kiddy\'s',
				'kiddie'=>'kiddy',
				'kiddy'=>'kiddie',
				'kidnaped'=>'kidnapped',
				'kidnaper'=>'kidnapper',
				'kidnapers'=>'kidnappers',
				'kidnaping'=>'kidnapping',
				'kidnapings'=>'kidnappings',
				'kidnapped'=>'kidnaped',
				'kidnappee\'s'=>'kidnapee\'s',
				'kidnappee'=>'kidnapee',
				'kidnappees'=>'kidnapees',
				'kidnapper\'s'=>'kidnaper\'s',
				'kidnapper'=>'kidnaper',
				'kidnappers'=>'kidnapers',
				'kidnapping'=>'kidnaping',
				'kilogram\'s'=>'kilogramme\'s',
				'kilogram'=>'kilogramme',
				'kilograms'=>'kilogrammes',
				'kiloliter\'s'=>'kilolitre\'s',
				'kiloliter'=>'kilolitre',
				'kiloliters'=>'kilolitres',
				'kilometer\'s'=>'kilometre\'s',
				'kilometer'=>'kilometre',
				'kilometers'=>'kilometres',
				'kindergartner\'s'=>'kindergartener\'s',
				'kindergartner'=>'kindergartener',
				'kindergartners'=>'kindergarteners',
				'kindhearted'=>'kind-hearted',
				'kindheartedly'=>'kind-heartedly',
				'kindheartedness'=>'kind-heartedness',
				'kinestheses'=>'kinaestheses',
				'kinesthesia\'s'=>'kinaesthesia\'s',
				'kinesthesia'=>'kinaesthesia',
				'kinesthesias'=>'kinaesthesias',
				'kinesthesis\'s'=>'kinaesthesis\'s',
				'kinesthesis'=>'kinaesthesis',
				'kinesthetic'=>'kinaesthetic',
				'kinestheticallier'=>'kinaestheticallier',
				'kinestheticalliest'=>'kinaestheticalliest',
				'kinesthetically'=>'kinaesthetically',
				'kinestheticer'=>'kinaestheticer',
				'kinestheticest'=>'kinaestheticest',
				'kinesthetics'=>'kinaesthetics',
				'kipriyanovov'=>['kipriyanovov', 'kipriyanovoff',],
				'kireyevev'=>['kireyevev', 'kireyeveff',],
				'kirillovov'=>['kirillovov', 'kirillovoff',],
				'kirilovov'=>['kirilovov', 'kirilovoff',],
				'kirsanovov'=>['kirsanovov', 'kirsanovoff',],
				'kiryanovov'=>['kiryanovov', 'kiryanovoff',],
				'kissogram\'s'=>'kissagram\'s',
				'kissogram'=>'kissagram',
				'kissograms'=>'kissagrams',
				'klimovov'=>['klimovov', 'klimovoff',],
				'klimtsovov'=>['klimtsovov', 'klimtsovoff',],
				'klokovov'=>['klokovov', 'klokovoff',],
				'knickknack\'s'=>'nicknack\'s',
				'knickknack'=>'nicknack',
				'knickknacks'=>'nicknacks',
				'knockwurst\'s'=>'knackwurst\'s',
				'knockwurst'=>'knackwurst',
				'knockwursts'=>'knackwursts',
				'knyazevev'=>['knyazevev', 'knyazeveff',],
				'kochenkovov'=>['kochenkovov', 'kochenkovoff',],
				'kolesnikovov'=>['kolesnikovov', 'kolesnikovoff',],
				'kolesovov'=>['kolesovov', 'kolesovoff',],
				'kollerovov'=>['kollerovov', 'kollerovoff',],
				'kolobkovov'=>['kolobkovov', 'kolobkovoff',],
				'kolomnikovov'=>['kolomnikovov', 'kolomnikovoff',],
				'kolontayevev'=>['kolontayevev', 'kolontayeveff',],
				'kolosovov'=>['kolosovov', 'kolosovoff',],
				'koltsovov'=>['koltsovov', 'koltsovoff',],
				'kolupayevev'=>['kolupayevev', 'kolupayeveff',],
				'komarovov'=>['komarovov', 'komarovoff',],
				'komissarovov'=>['komissarovov', 'komissarovoff',],
				'komolovov'=>['komolovov', 'komolovoff',],
				'kondratyevev'=>['kondratyevev', 'kondratyeveff',],
				'kondurovov'=>['kondurovov', 'kondurovoff',],
				'konevev'=>['konevev', 'koneveff',],
				'konnikovov'=>['konnikovov', 'konnikovoff',],
				'konovalovov'=>['konovalovov', 'konovalovoff',],
				'konyakovov'=>['konyakovov', 'konyakovoff',],
				'konyashovov'=>['konyashovov', 'konyashovoff',],
				'kooky'=>'kookie',
				'kopeck\'s'=>['kopek\'s', 'copeck\'s',],
				'kopeck'=>['kopek', 'copeck',],
				'kopecks'=>['kopeks', 'copecks',],
				'kopsovov'=>['kopsovov', 'kopsovoff',],
				'koptsevev'=>['koptsevev', 'koptseveff',],
				'korablyovov'=>['korablyovov', 'korablyovoff',],
				'korenevev'=>['korenevev', 'koreneveff',],
				'kornevev'=>['kornevev', 'korneveff',],
				'korneyevev'=>['korneyevev', 'korneyeveff',],
				'kornilovov'=>['kornilovov', 'kornilovoff',],
				'korolyovov'=>['korolyovov', 'korolyovoff',],
				'korotayevev'=>['korotayevev', 'korotayeveff',],
				'koroteyevev'=>['koroteyevev', 'koroteyeveff',],
				'korotkovov'=>['korotkovov', 'korotkovoff',],
				'kortnevev'=>['kortnevev', 'kortneveff',],
				'koryavovov'=>['koryavovov', 'koryavovoff',],
				'korzhakovov'=>['korzhakovov', 'korzhakovoff',],
				'korzhevev'=>['korzhevev', 'korzheveff',],
				'kosarevev'=>['kosarevev', 'kosareveff',],
				'koshelevev'=>['koshelevev', 'kosheleveff',],
				'koskovov'=>['koskovov', 'koskovoff',],
				'kosomovov'=>['kosomovov', 'kosomovoff',],
				'kosorukovov'=>['kosorukovov', 'kosorukovoff',],
				'Kossean\'s'=>'Kossaean\'s',
				'Kossean'=>'Kossaean',
				'kostomarovov'=>['kostomarovov', 'kostomarovoff',],
				'kotovov'=>['kotovov', 'kotovoff',],
				'kovalyovov'=>['kovalyovov', 'kovalyovoff',],
				'kovrovov'=>['kovrovov', 'kovrovoff',],
				'kozakovov'=>['kozakovov', 'kozakovoff',],
				'kozhukhovov'=>['kozhukhovov', 'kozhukhovoff',],
				'kozhurovov'=>['kozhurovov', 'kozhurovoff',],
				'kozlovov'=>['kozlovov', 'kozlovoff',],
				'kozyrevev'=>['kozyrevev', 'kozyreveff',],
				'krasnopyorovov'=>['krasnopyorovov', 'krasnopyorovoff',],
				'krasnovov'=>['krasnovov', 'krasnovoff',],
				'krayevev'=>['krayevev', 'krayeveff',],
				'krivkovov'=>['krivkovov', 'krivkovoff',],
				'krivoukhovov'=>['krivoukhovov', 'krivoukhovoff',],
				'krivovov'=>['krivovov', 'krivovoff',],
				'Kropotkin'=>['Kropotkine', 'Krapotkine',],
				'kruglovov'=>['kruglovov', 'kruglovoff',],
				'krukovov'=>['krukovov', 'krukovoff',],
				'krupnovov'=>['krupnovov', 'krupnovoff',],
				'krutikovov'=>['krutikovov', 'krutikovoff',],
				'krutovov'=>['krutovov', 'krutovoff',],
				'krylovov'=>['krylovov', 'krylovoff',],
				'krymovov'=>['krymovov', 'krymovoff',],
				'krysovov'=>['krysovov', 'krysovoff',],
				'kryuchkovov'=>['kryuchkovov', 'kryuchkovoff',],
				'kryukovov'=>['kryukovov', 'kryukovoff',],
				'kublanovov'=>['kublanovov', 'kublanovoff',],
				'kudashovov'=>['kudashovov', 'kudashovoff',],
				'kudryashovov'=>['kudryashovov', 'kudryashovoff',],
				'kudryavtsevev'=>['kudryavtsevev', 'kudryavtseveff',],
				'kuimovov'=>['kuimovov', 'kuimovoff',],
				'kuklachyovov'=>['kuklachyovov', 'kuklachyovoff',],
				'kuklevev'=>['kuklevev', 'kukleveff',],
				'Kulak'=>['Kulak','Koulak',],
				'kulakovov'=>['kulakovov', 'kulakovoff',],
				'kulikovov'=>['kulikovov', 'kulikovoff',],
				'kumquat\'s'=>'cumquat\'s',
				'kumquat'=>'cumquat',
				'kumquats'=>'cumquats',
				'kuptsovov'=>['kuptsovov', 'kuptsovoff',],
				'kurbatovov'=>['kurbatovov', 'kurbatovoff',],
				'kurganovov'=>['kurganovov', 'kurganovoff',],
				'kurpatovov'=>['kurpatovov', 'kurpatovoff',],
				'kustovov'=>['kustovov', 'kustovoff',],
				'kutepovov'=>['kutepovov', 'kutepovoff',],
				'kutikovov'=>['kutikovov', 'kutikovoff',],
				'kutuzovov'=>['kutuzovov', 'kutuzovoff',],
				'kutyakovov'=>['kutyakovov', 'kutyakovoff',],
				'kuvayevev'=>['kuvayevev', 'kuvayeveff',],
				'kuznetsovov'=>['kuznetsovov', 'kuznetsovoff',],
				'kuzubovov'=>['kuzubovov', 'kuzubovoff',],
				'kvasovov'=>['kvasovov', 'kvasovoff',],
				'kyanization'=>'kyanisation',
				'kyanize'=>'kyanise',
				'kyanized'=>'kyanised',
				'kyanizes'=>'kyanises',
				'kyanizing'=>'kyanising',
				'kyles'=>'kyloes',
			];
		}
	}
	
?>