<?php
		
		/* UTF-8 TEST
		
			中文汉字漢字
		
		*/
		
						/*
						
							This file is from the HoldOffHunger/convert-british-to-american-spellings open-source project.
							
							Author: HoldOffHunger
							License: BSD 3-Clause
							URL: https://github.com/HoldOffHunger/convert-british-to-american-spellings
						
						*/
				
				/* AmericanBritishWords_V
					
					Class for American/British spelling variants for all words beginning with : V.
					
				*/

	class AmericanBritishWords_V {
			/* __construct($args)
			
				Constructor.
				
				Nothing to do here.
			
			*/
			
		public function __construct($args) {
			return TRUE;
		}
		
			/* AmericanBritishWords()
			
				List of US/UK spellings for words starting with : V.
			
			*/

		public function AmericanBritishWords() {
			return [
				'vaagmer'=>'vaagmaer',
				'vaccinization\'s'=>'vaccinisation\'s',
				'vaccinization'=>'vaccinisation',
				'vaccinizations'=>'vaccinisations',
				'vacuolization\'s'=>'vacuolisation\'s',
				'vacuolization'=>'vacuolisation',
				'vacuolizations'=>'vacuolisations',
				'vacuumize'=>'vacuumise',
				'vacuumized'=>'vacuumised',
				'vacuumizes'=>'vacuumises',
				'vacuumizing'=>'vacuumising',
				'vagabondize'=>'vagabondise',
				'vagabondized'=>'vagabondised',
				'vagabondizer'=>'vagabondiser',
				'vagabondizers'=>'vagabondisers',
				'vagabondizes'=>'vagabondises',
				'vagabondizing'=>'vagabondising',
				'vaginule'=>'vaginulae',
				'vagrantize'=>'vagrantise',
				'vagrantizes'=>'vagrantises',
				'vakhrushevev'=>['vakhrushevev', 'vakhrusheveff',],
				'valor\'s'=>'valour\'s',
				'valor'=>'valour',
				'valorization\'s'=>'valorisation\'s',
				'valorization'=>'valorisation',
				'valorizations'=>'valorisations',
				'valorize'=>'valorise',
				'valorized'=>'valorised',
				'valorizes'=>'valorises',
				'valorizing'=>'valorising',
				'valorousness'=>'valourousness',
				'valors'=>'valours',
				'valvule'=>'valvulae',
				'vampirize'=>'vampirise',
				'vampirized'=>'vampirised',
				'vampirizes'=>'vampirises',
				'vampirizing'=>'vampirising',
				'vandalization\'s'=>'vandalisation\'s',
				'vandalization'=>'vandalisation',
				'vandalizations'=>'vandalisations',
				'vandalize'=>'vandalise',
				'vandalized'=>'vandalised',
				'vandalizes'=>'vandalises',
				'vandalizing'=>'vandalising',
				'vapor\'s'=>'vapour\'s',
				'vapor'=>'vapour',
				'vaporabilities'=>'vapourabilities',
				'vaporability\'s'=>'vapourability\'s',
				'vaporability'=>'vapourability',
				'vaporable\'s'=>'vapourable\'s',
				'vaporable'=>'vapourable',
				'vaporables'=>'vapourables',
				'vapored'=>'vapoured',
				'vaporer\'s'=>'vapourer\'s',
				'vaporer'=>'vapourer',
				'vaporers'=>'vapourers',
				'vaporescent'=>'vapourescent',
				'vaporier'=>'vapourier',
				'vaporiest'=>'vapouriest',
				'vaporific'=>'vapourific',
				'vaporimeter\'s'=>'vapourimeter\'s',
				'vaporimeter'=>'vapourimeter',
				'vaporing\'s'=>'vapouring\'s',
				'vaporing'=>'vapouring',
				'vaporingly'=>'vapouringly',
				'vaporings'=>'vapourings',
				'vaporish'=>'vapourish',
				'vaporisher'=>'vapourisher',
				'vaporishest'=>'vapourishest',
				'vaporishness\'s'=>'vapourishness\'s',
				'vaporishness'=>'vapourishness',
				'vaporishnesses'=>'vapourishnesses',
				'vaporizable\'s'=>'vaporisable\'s',
				'vaporizable'=>'vaporisable',
				'vaporizabler'=>'vaporisabler',
				'vaporizables'=>'vaporisables',
				'vaporizablest'=>'vaporisablest',
				'vaporization\'s'=>'vaporisation\'s',
				'vaporization'=>'vaporisation',
				'vaporizations'=>'vaporisations',
				'vaporize'=>'vaporise',
				'vaporized'=>'vaporised',
				'vaporizer\'s'=>'vaporiser\'s',
				'vaporizer'=>'vaporiser',
				'vaporizers'=>'vaporisers',
				'vaporizes'=>'vaporises',
				'vaporizing'=>'vaporising',
				'vaporless'=>'vapourless',
				'vaporlesses'=>'vapourlesses',
				'vaporlike\'s'=>'vapourlike\'s',
				'vaporlike'=>'vapourlike',
				'vaporlikes'=>'vapourlikes',
				'vaporose'=>'vapourose',
				'vaporously'=>'vapourously',
				'vapors'=>'vapours',
				'vaporware'=>'vapourware',
				'vapory'=>'vapoury',
				'varennikovov'=>['varennikovov', 'varennikovoff',],
				'varfolomeyevev'=>['varfolomeyevev', 'varfolomeyeveff',],
				'varicolored\'s'=>'varicoloured\'s',
				'varicolored'=>'varicoloured',
				'varicoloredder'=>'varicolouredder',
				'varicoloreddest'=>'varicoloureddest',
				'varicoloreds'=>'varicoloureds',
				'varicolorous'=>'varicolourous',
				'variolization'=>'variolisation',
				'vascularization\'s'=>'vascularisation\'s',
				'vascularization'=>'vascularisation',
				'vascularizations'=>'vascularisations',
				'vascularize'=>'vascularise',
				'vascularized'=>'vascularised',
				'vascularizes'=>'vascularises',
				'vascularizing'=>'vascularising',
				'vasectomize'=>'vasectomise',
				'vasectomized'=>'vasectomised',
				'vasectomizes'=>'vasectomises',
				'vasectomizing'=>'vasectomising',
				'vasilyevev'=>['vasilyevev', 'vasilyeveff',],
				'vasnetsovov'=>['vasnetsovov', 'vasnetsovoff',],
				'vasnevev'=>['vasnevev', 'vasneveff',],
				'vassalization'=>'vassalisation',
				'vassalize'=>'vassalise',
				'vassalized'=>'vassalised',
				'vassalizes'=>'vassalises',
				'vassalizing'=>'vassalising',
				'Vaticanization\'s'=>'Vaticanisation\'s',
				'Vaticanization'=>'Vaticanisation',
				'Vaticanizations'=>'Vaticanisations',
				'Vaticanize\'s'=>'Vaticanise\'s',
				'Vaticanize'=>'Vaticanise',
				'Vaticanizes'=>'Vaticanises',
				'vavasor'=>'vavasour',
				'vavasors'=>'vavasours',
				'vavilovov'=>['vavilovov', 'vavilovoff',],
				'Ve\'s'=>'Voe\'s',
				'Ve'=>'Voe',
				'vectorizable'=>'vectorisable',
				'vectorization\'s'=>'vectorisation\'s',
				'vectorization'=>'vectorisation',
				'vectorizations'=>'vectorisations',
				'vectorize'=>'vectorise',
				'vectorized'=>'vectorised',
				'vectorizer'=>'vectoriser',
				'vectorizered'=>'vectorisered',
				'vectorizering'=>'vectorisering',
				'vectorizers'=>'vectorisers',
				'vectorizes'=>'vectorises',
				'vectorizing'=>'vectorising',
				'vedeneyevev'=>['vedeneyevev', 'vedeneyeveff',],
				'vedernikovov'=>['vedernikovov', 'vedernikovoff',],
				'veery'=>'verey',
				'vegetablize'=>'vegetablise',
				'vegetablizes'=>'vegetablises',
				'velarization\'s'=>'velarisation\'s',
				'velarization'=>'velarisation',
				'velarizations'=>'velarisations',
				'velarize'=>'velarise',
				'velarized'=>'velarised',
				'velarizes'=>'velarises',
				'velarizing'=>'velarising',
				'veld\'s'=>'veldt\'s',
				'veld'=>'veldt',
				'velds'=>'veldts',
				'venalization\'s'=>'venalisation\'s',
				'venalization'=>'venalisation',
				'venalizations'=>'venalisations',
				'venalize'=>'venalise',
				'venalizes'=>'venalises',
				'vendor\'s'=>'vender\'s',
				'vendor'=>'vender',
				'vendors'=>'venders',
				'venediktovov'=>['venediktovov', 'venediktovoff',],
				'venomization\'s'=>'venomisation\'s',
				'venomization'=>'venomisation',
				'venomizations'=>'venomisations',
				'venomize'=>'venomise',
				'venomizes'=>'venomises',
				'venter'=>'ventre',
				'venters'=>'ventres',
				'ventriloquize'=>'ventriloquise',
				'ventriloquized'=>'ventriloquised',
				'ventriloquizes'=>'ventriloquises',
				'ventriloquizing'=>'ventriloquising',
				'venule'=>'venulae',
				'veranda\'s'=>'verandah\'s',
				'veranda'=>'verandah',
				'verandas'=>'verandahs',
				'verbalizable'=>'verbalisable',
				'verbalization\'s'=>'verbalisation\'s',
				'verbalization'=>'verbalisation',
				'verbalizations'=>'verbalisations',
				'verbalize'=>'verbalise',
				'verbalized'=>'verbalised',
				'verbalizer\'s'=>'verbaliser\'s',
				'verbalizer'=>'verbaliser',
				'verbalizers'=>'verbalisers',
				'verbalizes'=>'verbalises',
				'verbalizing'=>'verbalising',
				'Vereschagin'=>['Vereschagin','Vereschaguine',],
				'vermeiled'=>'vermeilled',
				'vermeiles'=>'vermeilles',
				'vermeiling'=>'vermeilling',
				'vermilion\'s'=>'vermillion\'s',
				'vermilion'=>'vermillion',
				'vermilionize'=>'vermilionise',
				'vermilionizes'=>'vermilionises',
				'vernacularization\'s'=>'vernacularisation\'s',
				'vernacularization'=>'vernacularisation',
				'vernacularizations'=>'vernacularisations',
				'vernacularize'=>'vernacularise',
				'vernacularized'=>'vernacularised',
				'vernacularizes'=>'vernacularises',
				'vernacularizing'=>'vernacularising',
				'vernalization\'s'=>'vernalisation\'s',
				'vernalization'=>'vernalisation',
				'vernalizations'=>'vernalisations',
				'vernalize'=>'vernalise',
				'vernalized'=>'vernalised',
				'vernalizes'=>'vernalises',
				'vernalizing'=>'vernalising',
				'versicolor'=>'versicolour',
				'versicolorate'=>'versicolourate',
				'versicolored'=>'versicoloured',
				'versicolorous'=>'versicolourous',
				'versionize'=>'versionise',
				'versionizes'=>'versionises',
				'verticalize'=>'verticalise',
				'verticalized'=>'verticalised',
				'verticalizes'=>'verticalises',
				'verticalizing'=>'verticalising',
				'veselovov'=>['veselovov', 'veselovoff',],
				'vesicule'=>'vesiculae',
				'vestryize'=>'vestryise',
				'vestryizes'=>'vestryises',
				'veter\'s'=>'vetoer\'s',
				'veter'=>'vetoer',
				'veteranize'=>'veteranise',
				'veteranizes'=>'veteranises',
				'vetrovov'=>['vetrovov', 'vetrovoff',],
				'vialed'=>'vialled',
				'vialing'=>'vialling',
				'victimizable\'s'=>'victimisable\'s',
				'victimizable'=>'victimisable',
				'victimizables'=>'victimisables',
				'victimization\'s'=>'victimisation\'s',
				'victimization'=>'victimisation',
				'victimizations'=>'victimisations',
				'victimize'=>'victimise',
				'victimized'=>'victimised',
				'victimizer\'s'=>'victimiser\'s',
				'victimizer'=>'victimiser',
				'victimizers'=>'victimisers',
				'victimizes'=>'victimises',
				'victimizing'=>'victimising',
				'Victorianize\'s'=>'Victorianise\'s',
				'Victorianize'=>'Victorianise',
				'Victorianizes'=>'Victorianises',
				'victualage\'s'=>'victuallage\'s',
				'victualage'=>'victuallage',
				'victualages'=>'victuallages',
				'victualed'=>'victualled',
				'victualer\'s'=>'victualler\'s',
				'victualer'=>'victualler',
				'victualers'=>'victuallers',
				'victualess'=>'victualless',
				'victualing'=>'victualling',
				'videodisc\'s'=>'videodisk\'s',
				'videodisc'=>'videodisk',
				'videodiscs'=>'videodisks',
				'vier'=>'vire',
				'viers'=>'vires',
				'Vietnamization\'s'=>'Vietnamisation\'s',
				'Vietnamization'=>'Vietnamisation',
				'Vietnamize'=>'Vietnamise',
				'Vietnamized'=>'Vietnamised',
				'Vietnamizes'=>'Vietnamises',
				'Vietnamizing'=>'Vietnamising',
				'vigor\'s'=>'vigour\'s',
				'vigor'=>'vigour',
				'vigorless'=>'vigourless',
				'vigors'=>'vigours',
				'vikhrovov'=>['vikhrovov', 'vikhrovoff',],
				'villagization'=>'villagisation',
				'villagizations'=>'villagisations',
				'vinogradovov'=>['vinogradovov', 'vinogradovoff',],
				'vinokurovov'=>['vinokurovov', 'vinokurovoff',],
				'violet-colored'=>'violet-coloured',
				'viremia'=>'viraemia',
				'viremias'=>'viraemias',
				'viremic'=>'viraemic',
				'virilization'=>'virilisation',
				'virilizations'=>'virilisations',
				'virilized'=>'virilised',
				'virilizing'=>'virilising',
				'virtualization'=>'virtualisation',
				'virtualize'=>'virtualise',
				'virtualized'=>'virtualised',
				'virtualizes'=>'virtualises',
				'virtualizing'=>'virtualising',
				'virtuosi'=>['virtuosos', 'virtuosoes',],
				'visionize'=>'visionise',
				'visionizes'=>'visionises',
				'visor\'s'=>'vizor\'s',
				'visor'=>'vizor',
				'visors'=>'vizors',
				'visualizable'=>'visualisable',
				'visualization\'s'=>'visualisation\'s',
				'visualization'=>'visualisation',
				'visualizations'=>'visualisations',
				'visualize'=>'visualise',
				'visualized'=>'visualised',
				'visualizer\'s'=>'visualiser\'s',
				'visualizer'=>'visualiser',
				'visualizers'=>'visualisers',
				'visualizes'=>'visualises',
				'visualizing'=>'visualising',
				'vitalization\'s'=>'vitalisation\'s',
				'vitalization'=>'vitalisation',
				'vitalizations'=>'vitalisations',
				'vitalize'=>'vitalise',
				'vitalized'=>'vitalised',
				'vitalizer\'s'=>'vitaliser\'s',
				'vitalizer'=>'vitaliser',
				'vitalizers'=>'vitalisers',
				'vitalizes'=>'vitalises',
				'vitalizing\'s'=>'vitalising\'s',
				'vitalizing'=>'vitalising',
				'vitalizingly'=>'vitalisingly',
				'vitalizings'=>'vitalisings',
				'vitaminization'=>'vitaminisation',
				'vitaminize'=>'vitaminise',
				'vitaminized'=>'vitaminised',
				'vitaminizes'=>'vitaminises',
				'vitaminizing'=>'vitaminising',
				'vitriolizable\'s'=>'vitriolisable\'s',
				'vitriolizable'=>'vitriolisable',
				'vitriolizables'=>'vitriolisables',
				'vitriolization\'s'=>'vitriolisation\'s',
				'vitriolization'=>'vitriolisation',
				'vitriolizations'=>'vitriolisations',
				'vitriolize'=>'vitriolise',
				'vitriolized'=>'vitriolised',
				'vitriolizer'=>'vitrioliser',
				'vitriolizers'=>'vitriolisers',
				'vitriolizes'=>'vitriolises',
				'vitriolizing'=>'vitriolising',
				'vivandier'=>'vivandire',
				'viver'=>'vivre',
				'viverrine'=>'viverrinae',
				'vivers'=>'vivres',
				'vizard'=>'visard',
				'vizards'=>'visards',
				'vizied'=>'visied',
				'vizies'=>'visies',
				'vocalizable'=>'vocalisable',
				'vocalization\'s'=>'vocalisation\'s',
				'vocalization'=>'vocalisation',
				'vocalizations'=>'vocalisations',
				'vocalize'=>'vocalise',
				'vocalized'=>'vocalised',
				'vocalizer\'s'=>'vocaliser\'s',
				'vocalizer'=>'vocaliser',
				'vocalizers'=>'vocalisers',
				'vocalizes'=>'vocalises',
				'vocalizing'=>'vocalising',
				'vocationalization\'s'=>'vocationalisation\'s',
				'vocationalization'=>'vocationalisation',
				'vocationalizations'=>'vocationalisations',
				'vocationalize'=>'vocationalise',
				'vocationalized'=>'vocationalised',
				'vocationalizes'=>'vocationalises',
				'vocationalizing'=>'vocationalising',
				'vodovatovov'=>['vodovatovov', 'vodovatovoff',],
				'vodyanovov'=>['vodyanovov', 'vodyanovoff',],
				'volatilizable\'s'=>'volatilisable\'s',
				'volatilizable'=>'volatilisable',
				'volatilizabler'=>'volatilisabler',
				'volatilizables'=>'volatilisables',
				'volatilizablest'=>'volatilisablest',
				'volatilization\'s'=>'volatilisation\'s',
				'volatilization'=>'volatilisation',
				'volatilizations'=>'volatilisations',
				'volatilize'=>'volatilise',
				'volatilized'=>'volatilised',
				'volatilizer\'s'=>'volatiliser\'s',
				'volatilizer'=>'volatiliser',
				'volatilizers'=>'volatilisers',
				'volatilizes'=>'volatilises',
				'volatilizing'=>'volatilising',
				'volcanization'=>'volcanisation',
				'volcanizations'=>'volcanisations',
				'volcanize'=>'volcanise',
				'volcanized'=>'volcanised',
				'volcanizes'=>'volcanises',
				'volcanizing'=>'volcanising',
				'volikovov'=>['volikovov', 'volikovoff',],
				'volkovov'=>['volkovov', 'volkovoff',],
				'volosenkovov'=>['volosenkovov', 'volosenkovoff',],
				'voltize'=>'voltise',
				'voltizes'=>'voltises',
				'volvakovov'=>['volvakovov', 'volvakovoff',],
				'vorobyovov'=>['vorobyovov', 'vorobyovoff',],
				'voronkovov'=>['voronkovov', 'voronkovoff',],
				'voronovov'=>['voronovov', 'voronovoff',],
				'vorontsovov'=>['vorontsovov', 'vorontsovoff',],
				'voskoboynikovov'=>['voskoboynikovov', 'voskoboynikovoff',],
				'votyakovov'=>['votyakovov', 'votyakovoff',],
				'voweled'=>'vowelled',
				'voweling'=>'vowelling',
				'vowelization\'s'=>'vowelisation\'s',
				'vowelization'=>'vowelisation',
				'vowelizations'=>'vowelisations',
				'vowelize'=>'vowelise',
				'vowelized'=>'vowelised',
				'vowelizes'=>'vowelises',
				'vowelizing'=>'vowelising',
				'vulcanizable\'s'=>'vulcanisable\'s',
				'vulcanizable'=>'vulcanisable',
				'vulcanizabler'=>'vulcanisabler',
				'vulcanizables'=>'vulcanisables',
				'vulcanizablest'=>'vulcanisablest',
				'vulcanizate\'s'=>'vulcanisate\'s',
				'vulcanizate'=>'vulcanisate',
				'vulcanizates'=>'vulcanisates',
				'vulcanization\'s'=>'vulcanisation\'s',
				'vulcanization'=>'vulcanisation',
				'vulcanizations'=>'vulcanisations',
				'vulcanize'=>'vulcanise',
				'vulcanized'=>'vulcanised',
				'vulcanizer\'s'=>'vulcaniser\'s',
				'vulcanizer'=>'vulcaniser',
				'vulcanizers'=>'vulcanisers',
				'vulcanizes'=>'vulcanises',
				'vulcanizing'=>'vulcanising',
				'vulgarization\'s'=>'vulgarisation\'s',
				'vulgarization'=>'vulgarisation',
				'vulgarizations'=>'vulgarisations',
				'vulgarize'=>'vulgarise',
				'vulgarized'=>'vulgarised',
				'vulgarizer\'s'=>'vulgariser\'s',
				'vulgarizer'=>'vulgariser',
				'vulgarizers'=>'vulgarisers',
				'vulgarizes'=>'vulgarises',
				'vulgarizing'=>'vulgarising',
				'vyrypayevev'=>['vyrypayevev', 'vyrypayeveff',],
			];
		}
	}
	
?>
